# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7dfa91fd0ca48fee6c9c3fb811b04795f0c030f36884a3ef25a2eb65d1b131639d303ba760de0c5a5f500de982cf3233aa0c01ceb17ff5c2167023d0340424f7

test:
  secret_key_base: 438873922ef3d60a1a710c2de3b9279cca915880abcf8da82587a7dd6a37a5303b0d487bd5a21e20e6fe741a8fe239a6aadb9466695ee5906396b123cf7558ea

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
